### PR TITLE
Full site feature - Code review request

### PR DESCRIPTION
**Pull request by canriquez**
Project specifications

- building a heatmap of the Smashing magazine website
- Align all elements with float OR flex .
- Use article tag for all articles listed on the page.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
### Hi team!

### Your project looks good!  :+1: 
#### But there are a few things that need to be corrected:

* Kindly recommended checking HTML markup with this [validator](https://validator.w3.org/#validate_by_upload)

Now it shows a lot of ERRORs in your project

er

#### Page structure

##### Navigation bar

*  It uses `div` and positions elements as at the source page (content is not important) ([link to page](https://www.smashingmagazine.com/)) 

header

* Kindly recommended to add here elements as in original website, content is not important

#### Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history screenshot from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)


* Please remember that your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on. You can read more about it [here](https://microverse.pathwright.com/library/microverse-onboarding/86777/path/step/53987922/). I hope in the next project you can do this!



### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*

**Review by Anna-Myzukina — CHANGES_REQUESTED** [review]
The project still needs changes

**Review by nikasulo — APPROVED** [review]
# Fantastic work! @canriquez and @s0kil :rocket:.
Please merge and keep going with the same energy :1st_place_medal:

**Comment by canriquez** [comment]
> # Fantastic work! @canriquez and @s0kil 🚀.
> Please merge and keep going with the same energy 🥇

ThANKS Tolulope!

**Pull request merged**
